version: '3.9'

services:

    dev:
        image: cosmtrek/air
        working_dir: /root/app
        volumes:
            - .:/root/app
            - gopath:/go
        tmpfs:
            - /root/app/tmp:exec
        tty: true
        restart: unless-stopped
        entrypoint: bash -c "go get -u && go mod tidy && air"

volumes:
    gopath:
